plugins:
  sidebar_enable:
    default: false
    client: true
  sidebar_block_order:
    client: true
    type: list
    default: "latest_replies"
  sidebar_custom_content:
    type: text
    default: ''
    client: true
  sidebar_num_results:
    default: '6'
    client: true
